apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todoapp
type: Opaque
data:
  SECRET_KEY: "QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK"
  NAME: "dG9kb2Ri"  
  USER: "dG9kb2FwcHVzZXI=" 
  PASSWORD: "MTIzNA==" 
  HOST: bXlzcWwtMC5teXNxbC1oZWFkbGVzcy5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbA==  
  
  